server:
  port: 80
spring:

  application:
    name: gateway

  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        register: true
#        prefer-ip-address: true
#        hostname: 119.23.52.225
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  mvc:
    view:
      prefix: classpath:/static/
